version: "3.9"
services:
  frontend:
    build:
      context: ./itam-app # Указываем путь к папке с фронтендом
      dockerfile: DockerFile
    ports:
      - "3000:3000" # Прокидываем порт фронтенда
    depends_on:
      - backend # Фронтенд зависит от бэкенда
    environment:
      - API_URL=http://backend:5001 # Указываем API-URL с именем сервиса бэкенда

  backend:
    build:
      context: ./backend # Указываем путь к папке с бэкендом
    ports:
      - "5001:5001" # Прокидываем порт бэкенда
    environment:
      - NODE_ENV=production
