version: "3.9"

services:
  frontend:
    build:
      context: ./itam-app # Указываем путь к папке с фронтендом
      dockerfile: DockerFile
    restart: unless-stopped
    init: true
    expose: [3000]
    ports:
      - 443:443
      - 80:80
    volumes:
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
  static:
#   caddy:
#     image: caddy:latest
#     container_name: caddy
#     ports:
#       - "80:80"
#       - "443:443"
#     volumes:
#       - ./itam-app/Caddyfile:/etc/caddy/Caddyfile # Путь к Caddyfile
#       - caddy_data:/data
#       - caddy_config:/config
#     depends_on:
#       - frontend
#       - backend

