# Build stage
FROM node:lts as build-stage

# Устанавливаем рабочую директорию
WORKDIR /nuxtapp

# Копируем только необходимые файлы для установки зависимостей
COPY package.json package-lock.json ./  

# Копируем остальные файлы приложения
COPY . .

# Устанавливаем переменные окружения
ARG NUXT_PUBLIC_API
ENV NUXT_PUBLIC_API=${NUXT_PUBLIC_API}

# Устанавливаем зависимости и строим приложение
RUN npm install && \
    npm run build && \
    rm -rf /root/.npm

# Production stage
FROM caddy:2-alpine

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем Caddyfile для настройки
COPY Caddyfile /etc/caddy/Caddyfile

# Копируем собранные файлы из build-stage
COPY --from=build-stage /nuxtapp/.output/public /app/dist

# Устанавливаем статические файлы, которые Caddy будет обслуживать
COPY --from=build-stage /nuxtapp/.output/public /app/.output

# Экспонируем порт, на котором будет работать Caddy
EXPOSE 80

# Запускаем Caddy
CMD ["caddy", "run", "--config", "/etc/caddy/Caddyfile"]
