# Build stage
FROM node:lts as build-stage

# Устанавливаем рабочую директорию
WORKDIR /nuxtapp

# Копируем только необходимые файлы для установки зависимостей
COPY package.json package-lock.json ./  

# Копируем остальные файлы приложения
COPY . .

# Устанавливаем переменные окружения
ARG NUXT_PUBLIC_API
ENV NUXT_PUBLIC_API=${NUXT_PUBLIC_API}

# Устанавливаем зависимости и строим приложение
RUN npm install && \
    npm run build && \
    rm -rf /root/.npm

# Production stage
# Пример для Caddyfile
FROM caddy:2-alpine

WORKDIR /app

# Копируем Caddyfile
COPY Caddyfile /etc/caddy/Caddyfile

# Копируем сертификаты
COPY ./certs/my_certificate.crt /etc/caddy/certificates/my_certificate.crt
COPY ./certs/my_private.key /etc/caddy/certificates/my_private.key

# Копируем статические файлы
COPY --from=build-stage /nuxtapp/.output/public /app/dist

EXPOSE 80

CMD ["caddy", "run", "--config", "/etc/caddy/Caddyfile"]

