# Build stage
FROM node:lts as build-stage

# Устанавливаем рабочую директорию
WORKDIR /nuxtapp

# Копируем только необходимые файлы для установки зависимостей
COPY package.json package-lock.json ./  

# Копируем остальные файлы приложения
COPY . .

# Устанавливаем переменные окружения
ARG NUXT_PUBLIC_API
ENV NUXT_PUBLIC_API=${NUXT_PUBLIC_API}

# Устанавливаем зависимости и строим приложение
RUN npm install && \
    npm run build && \
    rm -rf /root/.npm

# Production stage
FROM node:lts as prod-stage

# Устанавливаем рабочую директорию
WORKDIR /nuxtapp

# Копируем собранные файлы из build-stage
COPY --from=build-stage /nuxtapp/.output/ ./.output/

# Экспонируем порт, на котором будет работать приложение
EXPOSE 3000

# Команда для запуска приложения
CMD [ "node", ".output/server/index.mjs" ]
